const home=document.getElementById('home'),view=document.getElementById('view'),q=document.getElementById('q');
let FULL=[];
function esc(s){return String(s??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]))}
function strip(s){const d=document.createElement('div');d.innerHTML=s||'';return(d.textContent||'').replace(/\s+/g,' ').trim()}
function cleanHtml(html){const d=new DOMParser().parseFromString(html||'','text/html');d.querySelectorAll('script,style,iframe,object,embed,form,input,button').forEach(e=>e.remove());d.querySelectorAll('*').forEach(e=>{[...e.attributes].forEach(a=>{if(/^on/i.test(a.name)||a.name==='style')e.removeAttribute(a.name);if((a.name==='href'||a.name==='src')&&/^javascript:/i.test(a.value))e.removeAttribute(a.name)})});return d.body.innerHTML}
function panel(html){home.classList.add('hidden');view.classList.remove('hidden');view.innerHTML=html;scrollTo({top:view.offsetTop-10,behavior:'smooth'})}function goHome(){view.classList.add('hidden');home.classList.remove('hidden');scrollTo({top:0,behavior:'smooth'})}function focusSearch(){goHome();q.focus();q.scrollIntoView({behavior:'smooth'})}
function showEncyclopedia(){let h=`<h2>أقسام الموسوعة <span class=badge>${ARTICLES.length} مادة</span></h2><div class=syncbox><b>المكتبة المحلية الكاملة</b><div id=syncText class=syncstatus>${FULL.length?`محفوظ محليًا: ${FULL.length} صفحة/مقالة`:'لم تتم المزامنة بعد'}</div><div class=syncbar><i id=syncBar></i></div><button onclick="syncLibrary(true)">تحديث النصوص من المصدر الرسمي</button></div>`;for(const [cat,s] of Object.entries(DATA)){h+=`<div class=card><h3>${cat}</h3>`;for(const [n,c] of Object.entries(s))h+=`<button class=series onclick='showSeries(${JSON.stringify(n)})'><span>${n}</span><span class=badge>${c}</span></button>`;h+='</div>'}panel(h)}
function showSeries(name){const a=ARTICLES.filter(x=>x.series===name);panel(`<button class=back onclick=showEncyclopedia()>→ الأقسام</button><h2>${esc(name)}</h2><div class=card>${a.map(x=>`<button class=article onclick='showArticle(${x.id})'><b>${esc(x.title)}</b><small>${esc(x.category)} · الجزء ${x.part}</small></button>`).join('')}</div>`)}
function norm(s){return String(s||'').replace(/[–—_-]/g,' ').replace(/[()]/g,' ').replace(/الجزء/g,'').replace(/\s+/g,' ').trim().toLowerCase()}
function matchFull(x){const nt=norm(x.title),ns=norm(x.series);return FULL.find(p=>{const t=norm(p.title);return t===nt||t.includes(nt)||nt.includes(t)||(t.includes(ns)&&new RegExp(`(^|\\D)${x.part}(\\D|$)`).test(t))})}
function showArticle(id){const x=ARTICLES.find(a=>a.id===id);if(!x)return;const p=matchFull(x),prev=ARTICLES.find(a=>a.series===x.series&&a.part===x.part-1),next=ARTICLES.find(a=>a.series===x.series&&a.part===x.part+1);let body=p?`<div class=sourceLine>${esc(p.published||'')} · محفوظ للقراءة دون إنترنت</div><div class=fulltext>${cleanHtml(p.content)}</div><button onclick="openOfficial('${String(p.url).replace(/'/g,"\\'")}')">فتح الأصل</button>`:`<p>لم تتم مطابقة النص المحلي لهذه المادة بعد. شغّل تحديث النصوص من صفحة الموسوعة عند توفر الإنترنت.</p><button onclick="syncLibrary(true)">تحديث النصوص الآن</button>`;panel(`<button class=back onclick='showSeries(${JSON.stringify(x.series)})'>→ ${esc(x.series)}</button><article class=card><div class=eyebrow>${esc(x.category)}</div><h2>${esc(x.title)}</h2>${body}</article><div class=pager>${prev?`<button onclick=showArticle(${prev.id})>السابق</button>`:''}${next?`<button onclick=showArticle(${next.id})>التالي</button>`:''}</div>`)}
function showLevels(){panel('<h2>مستويات القراءة</h2><p class=sourceLine>اضغط على أي مستوى لفتح مواد القراءة المرتبطة به.</p>'+LEVELS.map((x,i)=>`<a class="card result levelBtn" href="#level-${i}" data-level="${i}"><b>${x[0]} — ${x[1]}</b><small>${x[2]}</small></a>`).join(''))}
function showLevel(i){const x=LEVELS[i];if(!x)return;const limit=x[0]===9999?ARTICLES.length:Math.min(x[0],ARTICLES.length);const items=ARTICLES.slice(0,limit);panel(`<button class=back onclick=showLevels()>→ مستويات القراءة</button><h2>${esc(x[1])}</h2><div class=sourceLine>${esc(x[2])} · ${limit} مادة متاحة من الفهرس</div><div class=card>${items.map(a=>`<button class=article onclick=showArticle(${a.id})><b>${esc(a.title)}</b><small>${esc(a.category)} · ${esc(a.series)}</small></button>`).join('')}</div>`)}
function showCharter(){panel('<h2>ميثاق القراءة والاستخدام</h2><div class=card><p>الموسوعة تقدم طروحات فكرية وبحثية، ولا تُعامل مادتها بوصفها فتاوى شرعية ملزمة.</p><p>تحفظ النسخة المحلية نسبة المواد إلى مصدرها ومؤلفها.</p></div><button onclick="openOfficial(LINKS.home)">المصدر الرسمي</button>')}
function showBio(){panel(`<h2>${BIO.name}</h2><div class=card><h3>${BIO.en}</h3><p>${BIO.role}</p><p>${BIO.university}</p><p>${BIO.summary}</p><h3>المؤهلات العلمية</h3>${BIO.education.map(e=>`<p>• ${e}</p>`).join('')}</div><div class=actions><button onclick="openOfficial(LINKS.cv)">السيرة الرسمية</button><button onclick="openOfficial(LINKS.orcid)">ORCID</button></div>`)}
function showChannels(){panel(`<h2>القنوات والروابط الرسمية</h2><div class="card channels">${[['المدونة','home'],['أبدأ من هنا','start'],['الكتب','books'],['DOI','doi'],['النسخة الاحتياطية','backup'],['دعم البحث العلمي','support'],['اسأل الدكتور','ask'],['البث المباشر والمكتبة المرئية','live'],['YouTube','youtube'],['TikTok','tiktok'],['Telegram','telegram'],['WhatsApp','whatsapp'],['Facebook','facebook'],['السيرة الذاتية','cv'],['ORCID','orcid']].map(([n,k])=>`<button onclick="openOfficial(LINKS.${k})">${n}</button>`).join('')}</div>`)}
function showAbout(){panel(`<h2>حول التطبيق</h2><div class=card><p>يعمل الفهرس والواجهة دون اتصال. وعند إجراء المزامنة مرة واحدة، تُحفظ نصوص المصدر في قاعدة الجهاز لتبقى متاحة دون إنترنت.</p><p><b>الفهرس الأساسي: ${ARTICLES.length} مادة</b> · المحفوظ محليًا الآن: <b>${FULL.length}</b></p></div>`)}
function searchNow(){const term=q.value.trim().toLowerCase();if(!term)return;const fullHits=FULL.filter(p=>(p.title+' '+strip(p.content)).toLowerCase().includes(term)).slice(0,100);const idx=ARTICLES.filter(a=>(a.title+' '+a.series+' '+a.category).toLowerCase().includes(term)).slice(0,100);let h=`<h2>نتائج البحث <span class=badge>${fullHits.length+idx.length}</span></h2>`;h+=fullHits.map(p=>`<button class='card result' onclick='showFull(${JSON.stringify(p.key)})'><b>${esc(p.title)}</b><small>بحث داخل النص الكامل</small></button>`).join('');h+=idx.map(x=>`<button class='card result' onclick=showArticle(${x.id})><b>${esc(x.title)}</b><small>${esc(x.category)} · ${esc(x.series)}</small></button>`).join('');panel(h||'<div class=card>لا توجد نتيجة.</div>')}
function showFull(key){const p=FULL.find(x=>x.key===key);if(!p)return;panel(`<button class=back onclick=focusSearch()>→ البحث</button><article class=card><h2>${esc(p.title)}</h2><div class=sourceLine>${esc(p.published||'')} · محفوظ محليًا</div><div class=fulltext>${cleanHtml(p.content)}</div><button onclick="openOfficial('${String(p.url).replace(/'/g,"\\'")}')">فتح الأصل</button></article>`)}
q.addEventListener('keydown',e=>{if(e.key==='Enter')searchNow()});
function openOfficial(url){if(!navigator.onLine){toast('هذا الرابط يتطلب اتصالًا بالإنترنت');return}window.open(url,'_blank','noopener')}
function toast(t){const e=document.getElementById('toast');e.textContent=t;e.style.display='block';setTimeout(()=>e.style.display='none',2600)}
function dbOpen(){return new Promise((res,rej)=>{const r=indexedDB.open('rasheedOffline',1);r.onupgradeneeded=()=>r.result.createObjectStore('posts',{keyPath:'key'});r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function savePosts(posts){const db=await dbOpen();await new Promise((res,rej)=>{const tx=db.transaction('posts','readwrite'),st=tx.objectStore('posts');posts.forEach(p=>st.put(p));tx.oncomplete=res;tx.onerror=()=>rej(tx.error)})}
async function loadPosts(){try{const db=await dbOpen();FULL=await new Promise((res,rej)=>{const r=db.transaction('posts').objectStore('posts').getAll();r.onsuccess=()=>res(r.result||[]);r.onerror=()=>rej(r.error)});}catch(e){FULL=[]}}
function jsonp(url){return new Promise((res,rej)=>{const cb='__rj'+Date.now()+Math.random().toString(36).slice(2),s=document.createElement('script');window[cb]=d=>{delete window[cb];s.remove();res(d)};s.onerror=()=>{delete window[cb];s.remove();rej(new Error('network'))};s.src=url+(url.includes('?')?'&':'?')+'callback='+cb;document.head.appendChild(s);setTimeout(()=>{if(window[cb]){delete window[cb];s.remove();rej(new Error('timeout'))}},25000)})}
async function syncLibrary(manual=false){if(!navigator.onLine){if(manual)toast('تحتاج المزامنة الأولى إلى الإنترنت');return}let start=1,all=[],total=9999;try{while(start<=total){const u=`https://dr-rasheed.blogspot.com/feeds/posts/default?alt=json-in-script&max-results=150&start-index=${start}`;const d=await jsonp(u),f=d.feed||{},entries=f.entry||[];total=Number(f.openSearch$totalResults?.$t||entries.length);for(const e of entries){const alt=(e.link||[]).find(l=>l.rel==='alternate');all.push({key:e.id?.$t||alt?.href||String(start),title:e.title?.$t||'',content:e.content?.$t||e.summary?.$t||'',published:e.published?.$t?.slice(0,10)||'',url:alt?.href||LINKS.home})}start+=entries.length;if(!entries.length)break;const t=document.getElementById('syncText'),b=document.getElementById('syncBar');if(t)t.textContent=`جاري حفظ النصوص: ${Math.min(all.length,total)} / ${total}`;if(b)b.style.width=`${Math.min(100,all.length/Math.max(1,total)*100)}%`}await savePosts(all);FULL=all;toast(`تم حفظ ${FULL.length} مادة/صفحة محليًا`);if(manual)showEncyclopedia()}catch(e){if(manual)toast('تعذر الاتصال بالمصدر الآن؛ المحتوى المحفوظ سابقًا لم يتأثر')}}
(async()=>{await loadPosts();if(navigator.onLine&&FULL.length===0)syncLibrary(false)})();
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');


// V5: reliable iPhone/Safari navigation without depending on inline onclick.
function routeHash(){
  const h=(location.hash||'').replace(/^#/,'');
  if(h.startsWith('level-')){const i=Number(h.slice(6));if(Number.isInteger(i)&&LEVELS[i])showLevel(i);}
  else if(h==='levels')showLevels();
}
document.addEventListener('click',function(e){
  const a=e.target.closest('a[data-level]');
  if(a){e.preventDefault();const i=Number(a.dataset.level);location.hash='level-'+i;showLevel(i);}
});
window.addEventListener('hashchange',routeHash);
setTimeout(routeHash,0);
