const DATA={
"الدراسات":{"الجدليات":6,"كتاب لغة أم لسان (دراسة تحليلية)":6,"ماذا كتب في الزبور؟":6,"من هو (هو)":2,"هل لعلم الله حدود؟":5,"ومن الجبال جدد بيض وحمر مختلف ألوانها وغرابيب سود":2},
"الفقه":{"فقه الحج":11,"فقه الدعاء":7,"فقه الرجم":1,"فقه الزكاة":9,"فقه الصلاة":6,"فقه الصيام":5,"ما يؤكل وما لا يؤكل":2},
"القصص":{"حديث الإفك":6,"ربنا باعد بين أسفارنا":4,"قصة السامري":2,"قصة بداية الخلق":8,"قصة داوود":24,"قصة سليمان":17,"قصة عيسى":9,"قصة موسى":12,"قصة نبي الله لوط":14,"قصة نوح":2,"قصة يأجوج ومأجوج":7,"قصة يوسف":27,"قصة يونس":43},
"المجتمع":{"تعدد الزوجات":2,"جدلية الذكر والأنثى":6,"ماذا ستفعل النساء في الجنة":5,"والعلماء هم الظالمون":4},
"النظريات":{"النظرية العالمية الإسلامية لكشف أسرار الكون":4,"نظرية الأمانة":9,"نظرية التطور (نشوء وليس ترقي)":10},
"مواضيع متنوعة":{"تعاريف":1,"متفرقات":4}
};
const LEVELS=[[5,'قارئ مبتدئ','Beginner Reader'],[15,'قارئ نهم','Voracious Reader'],[30,'المستطلع','The Explorer'],[60,'الدارس','The Scholar'],[100,'المستنبط','The Deducer'],[150,'الناقد','The Critic'],[200,'المعتكف','The Devotee'],[250,'الناسك','The Ascetic'],[287,'الراسخ','The Firmly Grounded'],[9999,'المُدّكر','The Reflector']];
const LINKS={home:'https://dr-rasheed.blogspot.com/',portal:'https://www.dr-rasheed.com/',start:'https://dr-rasheed.blogspot.com/p/roadmap.html',books:'https://dr-rasheed.blogspot.com/p/books.html',cv:'https://dr-rasheed.blogspot.com/p/about.html',doi:'https://dr-rasheed.blogspot.com/p/doi.html',backup:'https://dr-rasheed-com.blogspot.com/',support:'https://dr-rasheed.blogspot.com/p/support-research.html',orcid:'https://orcid.org/0000-0002-6379-2215',ask:'https://notebooklm.google.com/notebook/f05584df-2eb7-40f2-ac1b-e9b2420add54?authuser=2',live:'https://dr-rasheed.blogspot.com/p/live.html',youtube:'https://www.youtube.com/@DrRasheed-official-channel',tiktok:'https://www.tiktok.com/@rasheedjarrah',telegram:'https://t.me/dr_Rasheed_com',whatsapp:'https://www.whatsapp.com/channel/0029Vb5cyBKDTkKC7JLyY71M',facebook:'https://www.facebook.com/rsaljarrah'};
const ARTICLES=[];let id=1;for(const [category,series] of Object.entries(DATA))for(const [name,count] of Object.entries(series))for(let part=1;part<=count;part++)ARTICLES.push({id:id++,category,series:name,part,title:count===1?name:`${name} (${part})`});
const BIO={name:'أ.د. رشيد الجراح',en:'Prof. Rasheed Al-Jarrah',role:'أستاذ اللغويات (اللغويات التطبيقية الإنجليزية)',university:'جامعة اليرموك — إربد، الأردن',summary:'أستاذ دكتور في اللغويات، يعمل في قسم اللغة الإنجليزية وآدابها بجامعة اليرموك، وله خبرة أكاديمية في التدريس والبحث العلمي والإشراف على الرسائل الجامعية. يهتم بربط النظريات اللغوية الحديثة بفهم النص القرآني وتدبره.',education:['2002 — دكتوراة في اللغويات التطبيقية الإنجليزية، جامعة بول ستيت، الولايات المتحدة','1999 — ماجستير في اللغويات، جامعة بول ستيت، الولايات المتحدة','1994 — ماجستير في اللغة الإنجليزية (لغويات)، جامعة اليرموك، الأردن']};
